controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_controller:
      type: joint_group_position_controller/JointGroupPositionController

leg_controller:
  ros__parameters:
    joints:
      - zq1_Joint
      - zq2_Joint
      - zq3_Joint
      - zz1_Joint
      - zz2_Joint
      - zz3_Joint
      - zh1_Joint
      - zh2_Joint
      - zh3_Joint
      - yq1_Joint
      - yq2_Joint
      - yq3_Joint
      - yz1_Joint
      - yz2_Joint
      - yz3_Joint
      - yh1_Joint
      - yh2_Joint
      - yh3_Joint
    command_interfaces:
      - position
    state_interfaces:
      - position
