services:
  muto_rs:
    build:
      context: .
      dockerfile: Dockerfile.muto_rs
      args:
        ROS_DISTRO: ${ROS_DISTRO}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        USERNAME: ${USERNAME:-rosmaster}
    env_file:
      - .env
    volumes:
      - ./muto_ws:/muto_ws
    devices:
      - /dev:/dev
    privileged: true
    network_mode: host
    restart: unless-stopped
    stdin_open: true
    tty: true