controller_manager:
  ros__parameters:
    update_rate: 50 # <= 53

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_controller:
      type: position_controllers/JointGroupPositionController

leg_controller:
  ros__parameters:
    joints:
      # ─── CÔTÉ DROIT (RIGHT) ───
      - zq1_Joint # Avant Droit (Front Right) - Coxa
      - zq2_Joint # Avant Droit (Front Right) - Femur
      - zq3_Joint # Avant Droit (Front Right) - Tibia

      - zz1_Joint # Milieu Droit (Mid Right) - Coxa
      - zz2_Joint # Milieu Droit (Mid Right) - Femur
      - zz3_Joint # Milieu Droit (Mid Right) - Tibia

      - zh1_Joint # Arrière Droit (Rear Right) - Coxa
      - zh2_Joint # Arrière Droit (Rear Right) - Femur
      - zh3_Joint # Arrière Droit (Rear Right) - Tibia

      # ─── CÔTÉ GAUCHE (LEFT) ───
      - yq1_Joint # Avant Gauche (Front Left) - Coxa
      - yq2_Joint # Avant Gauche (Front Left) - Femur
      - yq3_Joint # Avant Gauche (Front Left) - Tibia

      - yz1_Joint # Milieu Gauche (Mid Left) - Coxa
      - yz2_Joint # Milieu Gauche (Mid Left) - Femur
      - yz3_Joint # Milieu Gauche (Mid Left) - Tibia

      - yh1_Joint # Arrière Gauche (Rear Left) - Coxa
      - yh2_Joint # Arrière Gauche (Rear Left) - Femur
      - yh3_Joint # Arrière Gauche (Rear Left) - Tibia
