controller_manager:
  ros__parameters:
    update_rate: 50 # <= 53

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    leg_controller:
      type: position_controllers/JointGroupPositionController

leg_controller:
  ros__parameters:
    joints:
      # ─── RIGHT SIDE ───
      - yq1_Joint # Front Right - Coxa
      - yq2_Joint # Front Right - Femur
      - yq3_Joint # Front Right - Tibia

      - yz1_Joint # Mid Right   - Coxa
      - yz2_Joint # Mid Right   - Femur
      - yz3_Joint # Mid Right   - Tibia

      - yh1_Joint # Rear Right  - Coxa
      - yh2_Joint # Rear Right  - Femur
      - yh3_Joint # Rear Right  - Tibia

      # ─── LEFT SIDE ───
      - zq1_Joint # Front Left  - Coxa
      - zq2_Joint # Front Left  - Femur
      - zq3_Joint # Front Left  - Tibia

      - zz1_Joint # Mid Left    - Coxa
      - zz2_Joint # Mid Left    - Femur
      - zz3_Joint # Mid Left    - Tibia

      - zh1_Joint # Rear Left   - Coxa
      - zh2_Joint # Rear Left   - Femur
      - zh3_Joint # Rear Left   - Tibia